main: io.github.jackzheng870.pingboard.PingboardPlugin
name: ${project.name}
version: ${project.version}
api-version: 1.16
author: Jack Zheng
website: https://github.com/jackzheng870/pingboard
commands:
  pingboard:
    description: Toggle Pingboard.
    usage: /<command>
    aliases: pb
